### ISSUE TITLE
你好作者，nuxtjs打包后出现无法显示提示框是哪里配置要改，我是用ssr渲染的

### ISSUE THREAD

**Issue by applelizihao** [thinkupp/vuetify-message-snackbar#1]
![image](https://user-images.githubusercontent.com/47731529/101163167-44974980-366e-11eb-97b8-4ad62b520c81.png)

**Comment by thinkupp** [comment]
不好意思刚看到你的问题
看上去像是CSS的问题，vuetify的组件可以正常显示和使用吗
