### ISSUE TITLE
Vue2无法显示提示框

### ISSUE THREAD

**Issue by Yingyya** [thinkupp/vuetify-message-snackbar#11]
你好，我在Vue2+Vuetify2中使用这个库不能显示提示框，我打开F12发现，并没有解析Vuetify组件，但是页面中的Vuetify组件可以正常使用，只有在这个库中不能使用。
![image](https://github.com/thinkupp/vuetify-message-snackbar/assets/76045884/0a4d233f-abc3-4a0b-b1ec-b5e556e0d697)
<img width="880" alt="image" src="https://github.com/thinkupp/vuetify-message-snackbar/assets/76045884/8680dd30-aced-4771-8bbf-e1caf5bbbadb">

**Comment by thinkupp** [comment]
请尝试将 v-snackbar 注册全局组件

**Comment by thinkupp** [comment]
https://github.com/thinkupp/vuetify-message-snackbar#%E7%BB%84%E4%BB%B6%E9%9C%80%E7%9F%A5

**Comment by Yingyya** [comment]
谢谢，已经解决了
