### ISSUE TITLE
不知道是不是我没能理解？

### ISSUE THREAD

**Issue by Tithy** [thinkupp/vuetify-message-snackbar#2]

**Comment by Tithy** [comment]
import message from 'vuetify-message-snackbar'
1.
使用：Vue.use(message[, option])
错误提示：TS7053: Element implicitly has an 'any' type because expression of type 'any' can't be used to index type 'NuxtMessageInit'.
TS2695: Left side of comma operator is unused and has no side effects.
TS1109: Expression expected.
2.
更改为Vue.use(message)无上述错误
调用列子：this.$message.warning('数量不满足')
错误提示：vue.runtime.esm.js?2b0e:619 [Vue warn]: Unknown custom element: <v-snackbar> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
 Unknown custom element: <v-icon> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
提示组件未注册，
不知道是不是使用方式不正确？

**Comment by thinkupp** [comment]
1、Vue.use(message, {} /* [, option]表示可选传参 */)
2、如果你是按需加载Vuetify，需要确保v-snackbar、v-btn、v-icon已经注册，比如下面这种写法：
`import Vuetify, { VSnackbar, VBtn, VIcon } from “vuetify/lib”;

Vue.use(Vuetify);
Vue.component("v-snackbar", VSnackbar);
Vue.component("v-btn", VBtn);
Vue.component("v-icon", VIcon)`

**Comment by thinkupp** [comment]
那这边我就先关了，有问题你再提
