### ISSUE TITLE
请问在axios拦截器里面怎么使用？

### ISSUE THREAD

**Issue by cairy** [thinkupp/vuetify-message-snackbar#4]
就是在拦截器里面都没有this的情况下，怎么调用。以前用elementui 直接引入 MessageBox可直接当函数用。这个怎么又。求个示例代码。

**Comment by thinkupp** [comment]
> 就是在拦截器里面都没有this的情况下，怎么调用。以前用elementui 直接引入 MessageBox可直接当函数用。这个怎么又。求个示例代码。

试一下 Vue.prototype.$message

**Comment by thinkupp** [comment]
请更新到最新版本，然后：

import { Notify } from "vuetify-message-snackbar";
Notify.success('use in js');
